### ISSUE TITLE
False leap year calculation for Persian calendar

### ISSUE THREAD

**Issue by bug-tracker** [kbwood/calendars#11]
Leap year calculation for Persian is more complicated than Gregorian. While the latter is simply every 4 years occurs, the Persian one has 7 cycles of 4 year, then 1 cycle of 5. Suppose we are starting from the first cycle: every 4 years we have a leap year; just normal. But, after 28 years (7x4), having a leap year, this is the end point of 4 year leap cycle. Now, after 5 years we have a leap year, i.e. 33 years (7x4+5) from the start. After this the whole cycle repeats.

As a real date example:
Persian years: 1342,1346,1350,1354,1358,1362,1366,1370 and also **1375** are all leap years.
Corresponding Gregorian: 1964,1968,1972,1976,1980,1984,1988,1992,**1997**

If you think it is complicated, you are right, but just because of this complication, the Persian calendar is among the most accurate calendars.

Thanks for you truly effort.
Cheers.

**Comment by kbwood** [comment]
That is what the Persian calendar does. The years you mentioned are all classified as leap years.

```
	var cal = $.calendars.instance('persian');
	for (var y = 1300; y < 1400; y++) {
		$('body').append('<p>' + y + ' ' + cal.leapYear(y) + '</p>');
	}
```

**Comment by bug-tracker** [comment]
You are absolutely right. The problem is in the presentation of the date picker (in your website) not in code itself. Your calendar rendering places the last month (Esfand) of the previous year just before the first month (Farvardin) of the queried year. And it's the cause of confusion at first glance. Some tweeking is needed anyway. Thanks.
