### ISSUE TITLE
How to convert the Hijri date (or any other than gregorian) to javascript Date?

### ISSUE THREAD

**Issue by zaher-elrody** [kbwood/calendars#12]
First, thanks for the great plugin. Second i would like to know how can i convert the CDate[] returned by the datepicker to an actual javascript date.

Regards,
Zaher

**Comment by kbwood** [comment]
Just call the _toJSDate_ function on each _CDate_.

**Comment by zaher-elrody** [comment]
Thank you, can you please tell me one more thing? how can convert from a javascript date to islamic date?

**Comment by kbwood** [comment]
Create an instance of the Islamic calendar and call its _fromJSDate _function.
