### ISSUE TITLE
How to use validation

### ISSUE THREAD

**Issue by a-mawlawi** [kbwood/calendars#26]
Hello,
Is there a clear documentation on how to use jquery.calendars.validation.js?

**Comment by kbwood** [comment]
The documentation is at http://keith-wood.name/calendarsPicker.html#validate. You need to add the Validator code, followed by _jquery.calendars.validation.js_ to your page before initialising your validation. The examples on the documentation page show the validation code used. The earlier inputs on the page are marked with the _cpDate_ classname to invoke the generic validation. More specialised cases are listed in the validation code, identifying the input by _name_ and applying the _cpCompareDate_ rule with extra parameters.

**Comment by a-mawlawi** [comment]
Hello,
Adding validation will only work on Gregorian date, I need this to work on Islamic date picker.
