### ISSUE TITLE
Calendars validation regionalOptions can not be overridden

### ISSUE THREAD

**Issue by a-mawlawi** [kbwood/calendars#27]
I'm trying to override regional options for jquery.calendars.validation.js but this is not possible.

**Comment by kbwood** [comment]
You need to set these values through the _calendarsPicker.setDefaults_ call, before applying the date picker to an element. E.g.:

```
$.calendarsPicker.setDefaults({validateDate: 'Wrong date'});
var islamic = $.calendars.instance('islamic');
$('#date').calendarsPicker({calendar: islamic, ... });
```

**Comment by a-mawlawi** [comment]
Thanks, this is working
