### ISSUE TITLE
inline Persian calendar seems squeezed

### ISSUE THREAD

**Issue by hungryfrank** [kbwood/calendars#32]
what I use the inline calender Persian the calendar(not tried with other ones) it is squeezed i have a whitespace about 1/3 of the width of calendar on the right side of the container and the controllers are squeezed in

**Comment by kbwood** [comment]
Can you provide a page that shows the problem?

**Comment by hungryfrank** [comment]
here is my html code

`
the two dropdown would go on top each other and there was a gap
I removed bold and they became ok and 
I added a fixed width of 220 px and it works now
.calendars-month {
	float: left;
	width: 18em;
	border: 1px solid #444;
	text-align: center;
    width: 220px;
}
I can post an image or the html code off the page
but I am having a problem with localization the Persian calendar
`<?php
/*
  $Id$

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2014 osCommerce

  Released under the GNU General Public License
*/
?>
<!DOCTYPE html>
<html <?php echo HTML_PARAMS; ?>>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET; ?>">
<meta name="robots" content="noindex,nofollow">
<title><?php echo TITLE; ?></title>
<base href="<?php echo ($request_type == 'SSL') ? HTTPS_SERVER . DIR_WS_HTTPS_ADMIN : HTTP_SERVER . DIR_WS_ADMIN; ?>" />

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo tep_catalog_href_link('ext/jquery/ui/redmond/jquery-ui-1.10.4.min.css', '', 'SSL'); ?>">
<script type="text/javascript" src="<?php echo tep_catalog_href_link('ext/jquery/jquery-2.2.3.min.js', '', 'SSL'); ?>"></script>
<script type="text/javascript" src="<?php echo tep_catalog_href_link('ext/jquery/ui/jquery-ui-1.10.4.min.js', '', 'SSL'); ?>"></script>
<?php
  echo $OSCOM_Hooks->call('siteWide', 'injectSiteStart');
 
?>

<link rel="stylesheet" href="includes/javascript/css/jquery.calendars.picker.css">
<script type="text/javascript" src="includes/javascript/js/jquery.plugin.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.plus.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.picker.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.picker.ext.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.persian.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.picker-fa.js"></script>
<script type="text/javascript" src="includes/javascript/js/jquery.calendars.persian-fa.js"></script>
 <script type="text/javascript" src="includes/javascript/js/jquery.datepick-fa.js"></script>

<script type="text/javascript" src="<?php echo tep_catalog_href_link('ext/flot/jquery.flot.min.js', '', 'SSL'); ?>"></script>
<script type="text/javascript" src="<?php echo tep_catalog_href_link('ext/flot/jquery.flot.time.min.js', '', 'SSL'); ?>"></script>
<link rel="stylesheet" type="text/css" href="includes/stylesheet.css">
<script type="text/javascript" src="includes/general.js"></script>
<script>
$(function() {
//	$.calendars.picker.setDefaults({renderer: $.calendars.picker.themeRollerRenderer}); // Requires jquery.calendars.picker.ext.js
	var calendar = $.calendars.instance('persian');
	$.datepick.setDefaults($.datepick.regionalOptions['fa']);
 // problematic line

	$('#popupDatepicker').calendarsPicker({calendar: calendar});
	$('#inlineDatepicker').calendarsPicker({calendar: calendar, onSelect: showDate});
});

function showDate(date) {
	alert('The date chosen is ' + date);
}

</script>
</head>
<body>

<div class="container-fluid">
  <div class="row">

<?php
  if (tep_session_is_registered('admin')) {
    require('includes/header.php');
    
    include('includes/column_left.php');
  } 
?>

  <div id="contentText" class="col">`
I get 
[Error] TypeError: undefined is not an object (evaluating '$.calendarsPicker.defaultRenderer')
	(anonymous function) (jquery.calendars.picker.ext.js:48)
	Global Code (jquery.calendars.picker.ext.js:282)
[Error] TypeError: undefined is not an object (evaluating '$.calendarsPicker.regionalOptions')
	(anonymous function) (jquery.calendars.picker-fa.js:7)
	Global Code (jquery.calendars.picker-fa.js:34)
[Error] TypeError: $.calendars.substituteDigits is not a function. (In '$.calendars.substituteDigits(['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'])', '$.calendars.substituteDigits' is undefined)
	(anonymous function) (jquery.calendars.persian-fa.js:17)
	Global Code (jquery.calendars.persian-fa.js:22)
[Error] TypeError: undefined is not an object (evaluating '$.datepick.regionalOptions')
	(anonymous function) (jquery.datepick-fa.js:7)
	Global Code (jquery.datepick-fa.js:43)
[Error] TypeError: undefined is not an object (evaluating '$.datepick.setDefaults')
	(anonymous function) (blob.php:37)
	i (jquery-2.2.3.min.js:2:27157)
	fireWith (jquery-2.2.3.min.js:2:27916)
	ready (jquery-2.2.3.min.js:2:29719)
	J (jquery-2.2.3.min.js:2:29898)

**Comment by kbwood** [comment]
`datepick` is a separate plugin to the calendars and its datepicker. So don't load `jquery.datepick-fa.js` and don't set any defaults on `$.datepick`.
The calendars datepicker plugin name is `calendarsPicker`, so your main code should be:
```
$(function() {
	$.calendarsPicker.setDefaults({renderer: $.calendarsPicker.themeRollerRenderer}); 
	var calendar = $.calendars.instance('persian');
	$('#popupDatepicker').calendarsPicker({calendar: calendar});
	$('#inlineDatepicker').calendarsPicker({calendar: calendar, onSelect: showDate});
});
```
