### ISSUE TITLE
umalquracalendar  the displayed date is behind the actual date 

### ISSUE THREAD

**Issue by ahgameel** [kbwood/calendars#37]
i have a problem with  umalquracalendar  the displayed date is behind the actual date as this example (02/06/1446) the current day date is (03/06/1446)

**Comment by kbwood** [comment]
I'm sorry about that, I had an outdated version of the calendar code on my web site. This has now been corrected.

The correct code is available for download from the calendar web site: http://keith-wood.name/calendars.html

**Comment by ahgameel** [comment]
Thanks Keith for your interest. I tried the correct code  and displayed
the correct date.
